@extends('layouts.app')
@section('title',$enum->label()) @section('header',$enum->label())
@section('content')
<div class="mb-6"><a href="{{route('documents.index',strtolower($enum->value))}}" class="mb-3 inline-flex items-center gap-1 text-sm font-semibold text-slate-500 hover:text-brand-600"><svg class="size-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-width="2" d="m15 18-6-6 6-6"/></svg>กลับไปรายการเอกสาร</a><h2 class="page-title">สร้างเอกสาร{{$enum->label()}}</h2><p class="page-subtitle">เพิ่มสินค้าได้หลายรายการ ตรวจสอบให้ถูกต้องก่อนยืนยัน POST</p></div>
<form id="docForm" method="post" action="{{route('documents.store',strtolower($enum->value))}}" class="space-y-6">@csrf<input type="hidden" name="idempotency_key" value="{{$idempotencyKey}}">
<section class="panel"><div class="panel-header"><div><h3 class="font-bold text-slate-900">ข้อมูลเอกสาร</h3><p class="text-xs text-slate-400">ข้อมูลอ้างอิงและรายละเอียดการรับ-จ่าย</p></div><span class="badge-amber">DRAFT</span></div><div class="panel-body grid gap-5 md:grid-cols-2 xl:grid-cols-3"><div><label class="label">วันที่ <span class="text-rose-500">*</span></label><input class="input" type="date" name="document_date" value="{{old('document_date',today()->format('Y-m-d'))}}" required></div><div><label class="label">คลัง <span class="text-rose-500">*</span></label><select class="select" name="warehouse_id" id="warehouse">@foreach($warehouses as $w)<option value="{{$w->id}}">{{$w->code}} — {{$w->name}}</option>@endforeach</select></div><div><label class="label">เลขอ้างอิง</label><input class="input" name="reference_no" value="{{old('reference_no')}}" placeholder="เลข PO / Invoice / ใบเบิก"></div><div><label class="label">ผู้ติดต่อ / แหล่งที่มา</label><input class="input" name="contact_name" value="{{old('contact_name')}}"></div><div><label class="label">แผนก</label><input class="input" name="department_name" value="{{old('department_name')}}"></div><div><label class="label">วัตถุประสงค์</label><input class="input" name="purpose" value="{{old('purpose')}}"></div><div class="md:col-span-2 xl:col-span-3"><label class="label">เหตุผล / หมายเหตุ @if(in_array($enum->value,['ADJUST_IN','ADJUST_OUT']))<span class="text-rose-500">*</span>@endif</label><textarea class="input min-h-20" name="note" @if(in_array($enum->value,['ADJUST_IN','ADJUST_OUT'])) required @endif>{{old('note')}}</textarea></div></div></section>
<section class="panel"><div class="panel-header"><div><h3 class="font-bold text-slate-900">รายการสินค้า</h3><p class="text-xs text-slate-400">ยิง Barcode เพื่อเพิ่มอย่างรวดเร็ว หรือกดปุ่มเพิ่มรายการ</p></div><button type="button" class="btn-secondary" id="add"><svg class="size-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-width="2" d="M12 5v14m7-7H5"/></svg>เพิ่มรายการ</button></div><div class="p-4 sm:p-6"><div class="relative mb-5"><svg class="absolute left-4 top-1/2 size-5 -translate-y-1/2 text-brand-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-width="1.8" d="M3 5v4m0 6v4m4-14v14m4-14v14m4-14v14m4-14v4m0 6v4"/></svg><input id="barcode" class="input border-brand-200 bg-brand-50/30 py-3 pl-12 text-base focus:bg-white" placeholder="ยิง Barcode หรือพิมพ์รหัสสินค้า แล้วกด Enter" autofocus></div><div class="table-wrap rounded-xl border border-slate-200"><table class="data-table" id="items"><thead><tr><th class="min-w-72">สินค้า</th><th>ยอดปัจจุบัน</th><th class="min-w-40">จำนวน</th><th>หน่วย</th><th></th></tr></thead><tbody></tbody></table></div></div></section>
<div class="sticky bottom-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white/95 p-4 shadow-xl shadow-slate-300/40 backdrop-blur"><p class="text-sm text-slate-500"><svg class="mr-1 inline size-4 text-amber-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-width="2" d="M12 9v4m0 4h.01M10.3 3.8 2.2 18a2 2 0 0 0 1.7 3h16.2a2 2 0 0 0 1.7-3L13.7 3.8a2 2 0 0 0-3.4 0Z"/></svg>หลัง POST แล้วจะไม่สามารถแก้ไขรายการได้</p><div class="flex gap-3"><a class="btn-secondary" href="{{route('documents.index',strtolower($enum->value))}}">ยกเลิก</a><button class="btn-success px-6" type="submit"><svg class="size-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-width="2" d="M5 12.5 9.5 17 19 7"/></svg>ยืนยันและ POST</button></div></div></form>
@endsection
@push('scripts')
<script>
const products=@json($productOptions);let n=0;const body=document.querySelector('#items tbody'),barcode=document.querySelector('#barcode');
function documentProductPicture(product){return product?.image?`<img src="${product.image}" data-product="${product.id}" class="document-product-picture size-12 shrink-0 rounded-xl border border-slate-200 bg-white object-cover" alt="รูปสินค้า">`:`<span data-product="${product?.id??''}" class="document-product-picture grid size-12 shrink-0 place-items-center rounded-xl border border-slate-200 bg-slate-100 text-slate-400">▧</span>`}
function add(p){if(!p)p=products[0];if(!p)return;const wh=document.querySelector('#warehouse').value,b=p.balances[wh]??'0.0000';const tr=document.createElement('tr');tr.innerHTML=`<td><select class="select product" name="items[${n}][product_id]">${products.map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${x.code} — ${x.name}</option>`).join('')}</select></td><td class="balance font-bold text-slate-900">${b}</td><td><input class="input" type="number" min="0.0001" step="0.0001" name="items[${n}][quantity]" required></td><td class="unit">${p.unit}</td><td class="text-right"><button type="button" class="remove rounded-lg p-2 text-rose-500 hover:bg-rose-50" aria-label="ลบ"><svg class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-width="1.8" d="M6 7h12m-9 0V4h6v3m-7 0 1 14h6l1-14M10 11v6m4-6v6"/></svg></button></td>`;body.append(tr);n++;tr.querySelector('.remove').onclick=()=>tr.remove();tr.querySelector('.product').onchange=e=>{let x=products.find(y=>y.id==e.target.value);tr.querySelector('.balance').textContent=x.balances[document.querySelector('#warehouse').value]??'0.0000';tr.querySelector('.unit').textContent=x.unit};tr.querySelector('input[type=number]').focus()}
document.querySelector('#add').onclick=()=>add();barcode.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();let v=barcode.value.trim().toLowerCase(),p=products.find(x=>x.code.toLowerCase()===v||(x.barcode??'').toLowerCase()===v);if(p){add(p);barcode.value=''}else alert('ไม่พบสินค้า')}};document.querySelector('#docForm').onsubmit=e=>{if(!body.children.length){e.preventDefault();alert('กรุณาเพิ่มสินค้าอย่างน้อย 1 รายการ');return}if(!confirm('ยืนยัน POST เอกสาร? เมื่อ POST แล้วจะแก้ไขรายการไม่ได้'))e.preventDefault()};add();
// Scanner mode: USB scanners work as keyboards and normally send Enter after the code.
body.innerHTML='';
barcode.closest('.relative').insertAdjacentHTML('afterend','<div id="scan-status" class="-mt-3 mb-5 hidden items-center gap-2 rounded-xl px-4 py-3 text-sm font-semibold"></div>');
const scanStatus=document.querySelector('#scan-status');
function refreshDocumentPictures(){body.querySelectorAll('tr').forEach(row=>{const select=row.querySelector('.product');if(!select)return;const product=products.find(item=>String(item.id)===String(select.value));let picture=row.querySelector('.document-product-picture');if(String(picture?.dataset.product)===String(product?.id??''))return;if(picture)picture.remove();select.insertAdjacentHTML('beforebegin',documentProductPicture(product));select.parentElement.classList.add('flex','items-center','gap-3')})}
new MutationObserver(refreshDocumentPictures).observe(body,{childList:true});body.addEventListener('change',event=>{if(event.target.classList.contains('product'))refreshDocumentPictures()});
function scanFeedback(message,success=true){scanStatus.className=`-mt-3 mb-5 flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-semibold ${success?'bg-emerald-50 text-emerald-700 ring-1 ring-emerald-200':'bg-rose-50 text-rose-700 ring-1 ring-rose-200'}`;scanStatus.textContent=`${success?'✓':'!'} ${message}`;barcode.classList.toggle('border-emerald-500',success);barcode.classList.toggle('border-rose-500',!success);setTimeout(()=>{barcode.classList.remove('border-emerald-500','border-rose-500')},700)}
function beep(){try{const context=new(window.AudioContext||window.webkitAudioContext)(),oscillator=context.createOscillator(),gain=context.createGain();oscillator.connect(gain);gain.connect(context.destination);oscillator.frequency.value=880;gain.gain.value=.05;oscillator.start();oscillator.stop(context.currentTime+.07)}catch(error){}}
barcode.onkeydown=e=>{if(!['Enter','Tab'].includes(e.key))return;e.preventDefault();const value=barcode.value.trim().toLowerCase();if(!value)return;const product=products.find(item=>item.code.toLowerCase()===value||(item.barcode??'').toLowerCase()===value);if(!product){scanFeedback(`ไม่พบ Barcode หรือรหัสสินค้า “${barcode.value.trim()}”`,false);barcode.select();return}const existing=[...body.querySelectorAll('tr')].find(row=>row.querySelector('.product')?.value==product.id);if(existing){const quantity=existing.querySelector('input[type=number]');quantity.value=(Number(quantity.value)||0)+1;existing.classList.add('bg-emerald-50');setTimeout(()=>existing.classList.remove('bg-emerald-50'),500);scanFeedback(`${product.code} — เพิ่มจำนวนเป็น ${quantity.value}`)}else{add(product);const row=body.lastElementChild;row.querySelector('input[type=number]').value=1;scanFeedback(`${product.code} — เพิ่มรายการ จำนวน 1`)}beep();barcode.value='';barcode.focus()};
document.addEventListener('click',()=>{if(!document.activeElement.closest('input,select,textarea,button,a'))barcode.focus()});
</script>
@endpush
