@extends('layouts.app') @section('title','Stock Card') @section('header','Stock Card')
@section('content')
<div class="mb-6"><h2 class="page-title">Stock Card</h2><p class="page-subtitle">ประวัติการเคลื่อนไหวและยอดคงเหลือหลังรายการ</p></div>
<form class="panel mb-5 flex flex-col gap-3 p-4 sm:flex-row"><select class="select flex-1" name="product_id"><option value="">เลือกสินค้าที่ต้องการดู</option>@foreach($products as $p)<option value="{{$p->id}}" @selected(request('product_id')==$p->id)>{{$p->code}} — {{$p->name}}</option>@endforeach</select><button class="btn-primary">แสดง Stock Card</button></form>
@if($transactions)
@php($selectedProduct = $products->firstWhere('id', (int) request('product_id')))
@if($selectedProduct)<div class="panel mb-5 flex items-center gap-4 p-5"><x-product-image :product="$selectedProduct" size="lg" /><div><span class="text-sm font-semibold text-slate-500">สินค้าที่กำลังแสดง</span><h3 class="text-xl font-bold text-slate-950">{{$selectedProduct->code}} — {{$selectedProduct->name}}</h3></div></div>@endif
<div class="table-shell"><div class="table-wrap"><table class="data-table"><thead><tr><th>วันเวลา</th><th>เอกสาร</th><th>ประเภท</th><th class="text-right">รับ</th><th class="text-right">จ่าย</th><th class="text-right">คงเหลือ</th><th>ผู้ทำรายการ</th></tr></thead><tbody>@forelse($transactions as $t)<tr><td class="whitespace-nowrap text-xs">{{$t->occurred_at->format('d/m/Y H:i:s')}}</td><td><a class="font-bold text-brand-600 hover:underline" href="{{route('documents.show',$t->document)}}">{{$t->document->document_no}}</a></td><td><span class="badge-slate">{{$t->transaction_type->value}}</span></td><td class="text-right font-semibold text-emerald-600">{{$t->quantity_in}}</td><td class="text-right font-semibold text-rose-600">{{$t->quantity_out}}</td><td class="text-right font-bold text-slate-900">{{$t->balance_after}}</td><td>{{$t->user->name}}</td></tr>@empty<tr><td colspan="7" class="empty-state">ไม่พบประวัติ</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-100 px-5 py-4">{{$transactions->links()}}</div></div>
@else<div class="panel empty-state"><svg class="mx-auto mb-3 size-12 text-slate-300" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M6 2h9l5 5v15H6a2 2 0 0 1-2-2V4c0-1.1.9-2 2-2Zm8 1v5h5M8 13h8M8 17h6"/></svg>เลือกสินค้าเพื่อแสดง Stock Card</div>@endif
@endsection
