@extends('layouts.app') @section('title','ตั้งค่าระบบ') @section('header','ตั้งค่าระบบ')
@section('content')
<div class="mb-6"><h2 class="page-title">ข้อมูลพื้นฐาน</h2><p class="page-subtitle">เพิ่ม แก้ไข ปิดใช้งาน หรือลบหน่วยนับและคลังสินค้าได้จากหน้านี้</p></div>
<div class="grid gap-6 xl:grid-cols-2">
<section class="panel"><div class="panel-header"><div><h3 class="font-bold text-slate-900">หน่วยนับ</h3><p class="text-xs text-slate-400">ต้องเพิ่มหน่วยนับก่อนสร้างสินค้า</p></div><span class="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><svg class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-width="1.8" d="M4 6h16M6 3v6m4-6v3m4-3v6m4-6v3M4 12h16M4 18h16"/></svg></span></div>
<form class="grid gap-3 border-b border-slate-100 p-5 sm:grid-cols-[140px_1fr_auto]" method="post" action="{{route('settings.units')}}">@csrf<input class="input" name="code" placeholder="รหัส เช่น PCS" required><input class="input" name="name" placeholder="ชื่อ เช่น ชิ้น" required><button class="btn-primary"><svg class="size-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-width="2" d="M12 5v14m7-7H5"/></svg>เพิ่ม</button></form>
<div class="table-wrap"><table class="data-table"><thead><tr><th>รหัส</th><th>ชื่อหน่วย</th><th>สถานะ</th><th></th></tr></thead><tbody>@forelse($units as $u)<tr><td class="font-bold text-slate-900">{{$u->code}}</td><td>{{$u->name}}</td><td><span class="{{$u->is_active?'badge-green':'badge-slate'}}">{{$u->is_active?'ใช้งาน':'ปิดใช้งาน'}}</span></td><td class="text-right"><div class="flex justify-end gap-1"><button type="button" class="btn-ghost px-3 py-2" data-id="{{$u->id}}" data-code="{{$u->code}}" data-name="{{$u->name}}" data-active="{{$u->is_active ? 1 : 0}}" onclick="editUnit(this)">แก้ไข</button><form method="post" action="{{route('settings.units.destroy',$u)}}" onsubmit="return confirm('ยืนยันลบหน่วยนับนี้? หากถูกใช้งาน ระบบจะปิดใช้งานแทน')">@csrf @method('DELETE')<button class="rounded-lg p-2 text-rose-500 hover:bg-rose-50" title="ลบ"><svg class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-width="1.8" d="M6 7h12m-9 0V4h6v3m-7 0 1 14h6l1-14"/></svg></button></form></div></td></tr>@empty<tr><td colspan="4" class="empty-state">ยังไม่มีหน่วยนับ กรุณาเพิ่มหน่วยแรก</td></tr>@endforelse</tbody></table></div></section>

<section class="panel"><div class="panel-header"><div><h3 class="font-bold text-slate-900">คลังสินค้า</h3><p class="text-xs text-slate-400">เลือกคลังเมื่อทำเอกสารรับและจ่าย</p></div><span class="grid size-10 place-items-center rounded-xl bg-violet-50 text-violet-600"><svg class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M3 21h18M5 21V8l7-5 7 5v13M9 21v-5h6v5"/></svg></span></div>
<form class="grid gap-3 border-b border-slate-100 p-5 sm:grid-cols-2" method="post" action="{{route('settings.warehouses')}}">@csrf<input class="input" name="code" placeholder="รหัส เช่น MAIN" required><input class="input" name="name" placeholder="ชื่อคลัง" required><input class="input sm:col-span-2" name="address" placeholder="ที่อยู่/รายละเอียดคลัง (ไม่บังคับ)"><button class="btn-primary sm:col-span-2"><svg class="size-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-width="2" d="M12 5v14m7-7H5"/></svg>เพิ่มคลัง</button></form>
<div class="table-wrap"><table class="data-table"><thead><tr><th>รหัส/คลัง</th><th>สถานะ</th><th></th></tr></thead><tbody>@forelse($warehouses as $w)<tr><td><strong class="block text-slate-900">{{$w->code}} — {{$w->name}}</strong><span class="text-xs text-slate-400">{{$w->address?:'ไม่ระบุที่อยู่'}}</span></td><td><span class="{{$w->is_active?'badge-green':'badge-slate'}}">{{$w->is_active?'ใช้งาน':'ปิดใช้งาน'}}</span></td><td class="text-right"><div class="flex justify-end gap-1"><button type="button" class="btn-ghost px-3 py-2" data-id="{{$w->id}}" data-code="{{$w->code}}" data-name="{{$w->name}}" data-address="{{$w->address}}" data-active="{{$w->is_active ? 1 : 0}}" onclick="editWarehouse(this)">แก้ไข</button><form method="post" action="{{route('settings.warehouses.destroy',$w)}}" onsubmit="return confirm('ยืนยันลบคลังนี้? หากมีประวัติ ระบบจะปิดใช้งานแทน')">@csrf @method('DELETE')<button class="rounded-lg p-2 text-rose-500 hover:bg-rose-50" title="ลบ"><svg class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-width="1.8" d="M6 7h12m-9 0V4h6v3m-7 0 1 14h6l1-14"/></svg></button></form></div></td></tr>@empty<tr><td colspan="3" class="empty-state">ยังไม่มีคลังสินค้า กรุณาเพิ่มคลังแรก</td></tr>@endforelse</tbody></table></div></section></div>

<dialog id="unit-dialog" class="m-auto w-[calc(100%-2rem)] max-w-md rounded-2xl bg-white p-0 shadow-2xl backdrop:bg-slate-950/60"><form id="unit-edit-form" method="post">@csrf @method('PUT')<div class="panel-header"><h3 class="font-bold text-slate-900">แก้ไขหน่วยนับ</h3><button type="button" onclick="document.getElementById('unit-dialog').close()" class="text-slate-400">✕</button></div><div class="panel-body space-y-4"><div><label class="label">รหัส</label><input id="unit-code" class="input" name="code" required></div><div><label class="label">ชื่อหน่วย</label><input id="unit-name" class="input" name="name" required></div><label class="flex items-center gap-3 text-sm"><input id="unit-active" class="size-5 rounded border-slate-300 text-brand-600" type="checkbox" name="is_active" value="1"> เปิดใช้งาน</label></div><div class="flex justify-end gap-2 border-t border-slate-100 p-4"><button type="button" class="btn-secondary" onclick="document.getElementById('unit-dialog').close()">ยกเลิก</button><button class="btn-primary">บันทึก</button></div></form></dialog>
<dialog id="warehouse-dialog" class="m-auto w-[calc(100%-2rem)] max-w-lg rounded-2xl bg-white p-0 shadow-2xl backdrop:bg-slate-950/60"><form id="warehouse-edit-form" method="post">@csrf @method('PUT')<div class="panel-header"><h3 class="font-bold text-slate-900">แก้ไขคลังสินค้า</h3><button type="button" onclick="document.getElementById('warehouse-dialog').close()" class="text-slate-400">✕</button></div><div class="panel-body space-y-4"><div><label class="label">รหัส</label><input id="warehouse-code" class="input" name="code" required></div><div><label class="label">ชื่อคลัง</label><input id="warehouse-name" class="input" name="name" required></div><div><label class="label">ที่อยู่/รายละเอียด</label><textarea id="warehouse-address" class="input min-h-20" name="address"></textarea></div><label class="flex items-center gap-3 text-sm"><input id="warehouse-active" class="size-5 rounded border-slate-300 text-brand-600" type="checkbox" name="is_active" value="1"> เปิดใช้งาน</label></div><div class="flex justify-end gap-2 border-t border-slate-100 p-4"><button type="button" class="btn-secondary" onclick="document.getElementById('warehouse-dialog').close()">ยกเลิก</button><button class="btn-primary">บันทึก</button></div></form></dialog>
@endsection
@push('scripts')<script>
function editUnit(button){const data=button.dataset;const form=document.getElementById('unit-edit-form');form.action=`{{url('/settings/units')}}/${data.id}`;document.getElementById('unit-code').value=data.code;document.getElementById('unit-name').value=data.name;document.getElementById('unit-active').checked=data.active==='1';document.getElementById('unit-dialog').showModal()}
function editWarehouse(button){const data=button.dataset;const form=document.getElementById('warehouse-edit-form');form.action=`{{url('/settings/warehouses')}}/${data.id}`;document.getElementById('warehouse-code').value=data.code;document.getElementById('warehouse-name').value=data.name;document.getElementById('warehouse-address').value=data.address??'';document.getElementById('warehouse-active').checked=data.active==='1';document.getElementById('warehouse-dialog').showModal()}
</script>@endpush
